""" Plugins
packadd! matchit
packadd! termdebug

function! PackInit() abort
  packadd minpac

  call minpac#init()
  call minpac#add('k-takata/minpac', {'type': 'opt'})

  call minpac#add('alvan/vim-closetag')
  call minpac#add('arcticicestudio/nord-vim')
  call minpac#add('bling/vim-bufferline')
  call minpac#add('christoomey/vim-tmux-navigator')
  call minpac#add('honza/vim-snippets')
  call minpac#add('itchyny/lightline.vim')
  call minpac#add('jiangmiao/auto-pairs')
  call minpac#add('junegunn/fzf', {'do': '!./install --all'})
  call minpac#add('junegunn/fzf.vim')
  call minpac#add('junegunn/vim-peekaboo')
  call minpac#add('kana/vim-textobj-entire')
  call minpac#add('kana/vim-textobj-user')
  call minpac#add('liuchengxu/vista.vim')
  call minpac#add('ludovicchabant/vim-gutentags')
  call minpac#add('mbbill/undotree')
  call minpac#add('mhinz/vim-signify')
  call minpac#add('mhinz/vim-startify')
  call minpac#add('mtth/scratch.vim')
  call minpac#add('nelstrom/vim-visual-star-search')
  call minpac#add('neoclide/coc.nvim', {'branch': 'release'})
  call minpac#add('sheerun/vim-polyglot')
  call minpac#add('tpope/vim-commentary')
  call minpac#add('tpope/vim-dispatch')
  call minpac#add('tpope/vim-fugitive')
  call minpac#add('tpope/vim-repeat')
  call minpac#add('tpope/vim-surround')
  call minpac#add('tpope/vim-unimpaired')
  call minpac#add('tpope/vim-vinegar')
  call minpac#add('vim-scripts/a.vim')
endfunction

command! PackClean  call PackInit() | call minpac#clean()
command! PackStatus call PackInit() | call minpac#status()
command! PackUpdate call PackInit() |
  \ call minpac#update('', {'do': 'call minpac#status()'})

let g:coc_global_extensions = [
  \ 'coc-css',
  \ 'coc-eslint',
  \ 'coc-html',
  \ 'coc-json',
  \ 'coc-prettier',
  \ 'coc-rls',
  \ 'coc-snippets',
  \ 'coc-tsserver'
\ ]

let g:coc_user_config = {
  \ 'languageserver': {
    \ 'clangd': {
      \ 'command': 'clangd',
      \ 'args': ['--background-index'],
      \ 'filetypes': ['c', 'cpp']
    \ }
  \ }
\ }

command! -nargs=0 Prettier :CocCommand prettier.formatFile

let g:lightline = {'colorscheme': 'nord'}
let g:nord_cursor_line_number_background = 1
let g:signify_vcs_list = ['git', 'hg']
let g:startify_change_to_vcs_root = 1

let g:vista_sidebar_width = 50
noremap <silent> <Leader>v :<C-u>Vista!!<CR>

nnoremap <silent> <C-p> :<C-u>FZF<CR>
nnoremap <silent> <Leader>u :<C-u>UndotreeToggle<CR>

""" General
filetype plugin indent on

set autoread

nnoremap <silent> <Leader>ev :<C-u>vsplit $MYVIMRC<CR>
nnoremap <silent> <Leader>sv :<C-u>source $MYVIMRC<CR>

""" Autocompletion
set infercase

""" Backups
set backup
set backupdir=$HOME/.vim/backup
set directory=$HOME/.vim/swap

""" Buffers, Windows, and Tabs
set hidden
set splitbelow
set splitright

""" Editing
set backspace=indent,eol,start
set clipboard^=unnamed
set mouse=a
set scrolloff=5
set ttymouse=xterm2
set virtualedit=block

""" Folding
set foldlevelstart=99
set foldmethod=syntax

nnoremap <Space> za

function! VimFold(lnum) abort
  let l:line = getline(a:lnum)

  if l:line =~ '^""'
    return '>' . (matchend(l:line, '""*') - 2)
  endif

  return '='
endfunction

augroup filetype_vim
  autocmd!
  autocmd FileType vim
    \ setlocal foldlevel=0 |
    \ setlocal foldmethod=expr |
    \ setlocal foldexpr=VimFold(v:lnum)
augroup END

""" Indentation
set autoindent
set expandtab
set shiftwidth=2
set softtabstop=2

""" Search
set hlsearch
set ignorecase
set incsearch
set smartcase

nnoremap <silent> <Leader><Space> :<C-u>nohlsearch<CR><C-l>

""" Text
syntax enable

set encoding=utf-8

""" Undo
set undodir=$HOME/.vim/undo
set undofile

augroup disallow_persistent_undo
  autocmd!
  autocmd BufWritePre /tmp/* setlocal noundofile
augroup END

""" User Interface
set colorcolumn=80
set cursorline
set laststatus=2
set lazyredraw
set noshowmode
set number
set relativenumber
set showcmd
set showmatch
set termguicolors
set wildmenu

colorscheme nord

highlight TrailingWhitespace ctermbg=red guibg=red

augroup extra_whitespace
  autocmd!
  autocmd BufWinEnter * match TrailingWhitespace /\s\+$/
  autocmd BufWinLeave * call clearmatches()
augroup END
