# ==============================================================================
# Options
# ==============================================================================
# PREFIX: CTRL-a (this is easy to press if CAPS LOCK is remapped to CTRL)
unbind C-b
set -g prefix C-a

# Make windows and panes be 1-indexed to match the physical ordering of the keys
set -g base-index 1
setw -g pane-base-index 1

# Display things in 256 colors with 24-bit color support
set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ',xterm-256color:Tc'

set -g clock-mode-style 12

# ==============================================================================
# Key Bindings
# ==============================================================================
# Send SIGQUIT to programs running under tmux: "PREFIX CTRL-\"
bind C-\\ send C-\\

# Clear the terminal screen: PREFIX CTRL-l
bind C-l send C-l

# Open a new window in the current directory: PREFIX c
bind c new-window -c '#{pane_current_path}'

# Navigate to the previous/next window: PREFIX CTRL-{j,k}
bind -r C-j previous-window
bind -r C-k next-window

# Move the current window one position left/right: PREFIX {<,>}
bind -r < swap-window -t -1
bind -r > swap-window -t +1

# Resize the current pane by 5 lines: PREFIX {H,J,K,L}
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Split the current pane in its directory: PREFIX {|,-}
unbind %
bind | split-window -h -c '#{pane_current_path}'
unbind '"'
bind - split-window -v -c '#{pane_current_path}'

# Same as above, but split with full height/width: PREFIX {\,_}
bind \\ split-window -fh -c '#{pane_current_path}'
bind _ split-window -fv -c '#{pane_current_path}'

# ==============================================================================
# Copy Mode
# ==============================================================================
# Navigate copy mode with vi key bindings
setw -g mode-keys vi

# Switch to copy mode: PREFIX <Esc>
unbind [
bind Escape copy-mode

# Switch to visual mode to select text (from within copy mode): v
bind -T copy-mode-vi v send -X begin-selection

# Toggle blockwise selection (from within visual mode): r
bind -T copy-mode-vi r send -X rectangle-toggle

# Paste text in the buffer: PREFIX p
unbind ]
bind p paste-buffer

# ==============================================================================
# Plugins
# ==============================================================================
set -g @plugin 'arcticicestudio/nord-tmux'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g @continuum-restore 'on'
set -g @prefix_highlight_show_copy_mode 'on'

run-shell -b "$HOME/.tmux/plugins/tpm/tpm"
